name: 'Codecov'
outbound-endpoints:
  - fqdn: storage.googleapis.com
    port: 443
    reason: to upload coverage report
  - fqdn: uploader.codecov.io
    port: 443
    reason: to download codecov uploader
  - fqdn: codecov.io
    port: 443
    reason: to download codecov uploader  
harden-runner-link: https://app.stepsecurity.io/github/step-security/secure-repo/actions/runs/1533156019