name: Add To GitHub projects
github-token:
  action-input:
    input: github-token
    is-default: false
  permissions:
    repository-projects: write
    repository-projects-reason: to assign issues and PRs to repo project
