name: "Nx set SHAs"
github-token:
  environment-variable-name: GITHUB_TOKEN
  permissions:
    contents: read
    contents-reason: to fetch successful commit
    actions: read
    actions-reason:  to fetch successful wrokflow runs
  #References:https://github.com/nrwl/nx-set-shas/blob/8b116da380aced2121ab9ee569d2927a6661b3e9/find-successful-workflow.js#L97
  #Reference:https://github.com/nrwl/nx-set-shas#permissions-in-v2
