name: Get Current Pull Request
github-token:
  action-input:
    input: github-token
    is-default: false
  permissions:
     pull-requests: read
     pull-requests-reason: to get prs associated with commit
      #Reference:https://github.com/8BitJonny/gh-get-current-pr/blob/4e0fdd834a5f2713d0b4f03e3277521a540dcf75/src/main.ts#L12
