name: Job level env
on:
  pull_request:
    branches: [main]

jobs:
  job-with-error:
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: some step that uses token
        run: |
          npm ci