name: 'Git Commit and Push'
github-token:
  action-input:
    input: github-token
    is-default: false
  permissions:
    contents: write
    contents-reason: to commit the changes
    #Refernces: https://github.com/github-actions-x/commit/blob/722d56b8968bf00ced78407bbe2ead81062d8baa/entrypoint.py#L23
   
