name: "GitHub Release Assets Upload Action"
github-token:
  environment-variable-name: GITHUB_TOKEN
  permissions:
    contents: write
    contents-reason: to upload release assets
#Reference: https://github.com/dwenegar/upload-release-assets/blob/fc5bc557b51cf4fc168f11bebc1e20a17949f0d2/src/upload-release-assets.ts#L50
