name: Integration Test Github
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: github/codeql-action/analyze@v3
    - uses: borales/actions-yarn@v2.3.0
      with:
        auth-token: ${{ secrets.GITHUB_TOKEN }}
        registry-url: npm.pkg.github.com
