name: "Deployment Status"
github-token:
  action-input:
    input: token
    is-default: false
  permissions:
    deployments: write 
    deployments-reason: to update status of deployments
    #Reference: https://github.com/chrnorm/deployment-status/blob/8a81fd4d7b467e95818f2c6a1b5b228de211e90c/src/main.ts
