name: "Code Coverage Report"
github-token:
  action-input:
    input: github_token
    is-default: false
  permissions:
    contents: write
    contents-reason: to create commit comment with code coverage
    issues: write 
    issues-reason: to comment code coverage on pr
    #Reference: https://github.com/eberlitz/lcov-reporter-action
