name: 'setup-php'
github-token:
  environment-variable-name: COMPOSER_TOKEN
  permissions:
    contents: read
    contents-reason: to clone the repos and get release assets #Reference: https://github.com/shivammathur/setup-php/blob/c38f1acc3878025148540820642612cec3b0bcf9/dist/index.js#L531
outbound-endpoints:
  - fqdn: '*.launchpad.net'
    port: 80
    reason: to call launchpad API to get PPA fingerprint and get packages
  - fqdn: '*.launchpad.net'
    port: 443
    reason: to call launchpad API to get PPA fingerprint and get packages
  - fqdn: '*.ubuntu.com'
    port: 80
    reason: to download packages from ubuntu archives
  - fqdn: '*.ubuntu.com'
    port: 443
    reason: to download packages from ubuntu archives
  - fqdn: bazel.build
    port: 443
    reason: to download bazel GPG key
  - fqdn: '*blackfire.io'
    port: 80
    reason: to set-up Blackfire
  - fqdn: '*blackfire.io'
    port: 443
    reason: to set-up Blackfire
  - fqdn: cdn.jsdelivr.net
    port: 443
    reason: to fetch scripts (fallback CDN)
  - fqdn: deployer.org
    port: 443
    reason: to download Deployer phar
  - fqdn: downloads.ioncube.com
    port: 443
    reason: to download ionCube extension
  - fqdn: download.oracle.com
    port: 443
    reason: to download Oracle instantclient
  - fqdn: getcomposer.org
    port: 443
    reason: to fetch Composer phars (fallback source)
  - fqdn: git.remirepo.net
    port: 443
    reason: to download patches
  - fqdn: '*.githubusercontent.com'
    port: 443
    reason: to fetch git objects, release information and code
  - fqdn: 'api.github.com'
    port: 443
    reason: to call GitHub API to get matching refs, releases and tags
  - fqdn: 'codeload.github.com'
    port: 443
    reason: to get GitHub release assets
  - fqdn: 'github.com'
    port: 443
    reason: to fetch code from GitHub
  - fqdn: packages.sury.org
    port: 443
    reason: to get PHP packages on Debian
  - fqdn: packages.sury.org
    port: 80
    reason: to get PHP packages on Debian
  - fqdn: '*.php.net'
    port: 443
    reason: to set-up PHP extensions
  - fqdn: '*.php.net'
    port: 80
    reason: to set-up PHP extensions
  - fqdn: phar.io
    port: 443
    reason: to download Phive phar
  - fqdn: phar.phpunit.de
    port: 443
    reason: to download PHPUnit and related phars
  - fqdn: repo.packagist.org
    port: 443
    reason: to get packages manifests using Composer
  - fqdn: setup-php.com
    port: 443
    reason: to set-up PPA mirrors, scripts and patches as fallback URL
  - fqdn: storage.googleapis.com
    port: 443
    reason: to set-up Bazel
  - fqdn: www.phing.info
    port: 443
    reason: to download phing phar
harden-runner-link: https://app.stepsecurity.io/github/shivammathur/test-setup-php/actions/runs/1539115993
