name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: &build_steps
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make build
  build-reproducible:
    runs-on: ubuntu-latest
    steps: *build_steps
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: make test
