name: test-custom-action-three-jobs
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Security Scanner
        uses: org/security-scanner@v3
        with:
          mode: strict
          scan-level: deep

      - uses: actions/checkout@v3
      - run: echo "build"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@v3
      - run: echo "lint"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "deploy"
