name: ci
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          # allow only github
          egress-policy: audit

      # Trailing comment for the checkout step.
      - name: Checkout
        uses: actions/checkout@v4
