version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      all:
        applies-to: version-updates
        patterns: ["*"]

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
          - "*"
