version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GH_PACKAGES_TOKEN }}

updates:
  # Frontend dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    registries:
      - npm-github
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - frontend
    commit-message:
      prefix: "deps"
      include: scope
    groups:
      # Group all production deps together to reduce PR noise
      production-deps:
        patterns:
          - "*"
        dependency-type: production
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: webpack
        update-types:
          - version-update:semver-major

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - ci
