version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - /app
    schedule:
      interval: daily

  - package-ecosystem: "nuget"
    directory: /app
    schedule:
      interval: daily
