name: Automate PR
on:
  issues:
    types:
      - labeled

permissions:
  contents: read

jobs:
  Automate:
    if: github.event.label.name == 'Automate'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      actions: write
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: step-security/secure-repo
    
      - name: Automate PR
        uses: step-security/secure-repo/Automate-PR@98ff385ea512d8ac7a1445f95e199f6864f439e1
        with:
          github-token: ${{secrets.PAT }}
          issue-id: ${{ github.event.issue.number}}