name: Knowledge-base Test
on:
  push:
    branches:
      - knowledge-base # to test new KBs

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read
concurrency:
  group: ${{ github.workflow }}
jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            proxy.golang.org:443
            sum.golang.org:443
            storage.googleapis.com:443
            objects.githubusercontent.com:443
            golang.org:443
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: 1.17
      - name: Run coverage
        run: go test ./...  -coverpkg=./... -race -coverprofile=coverage.txt -covermode=atomic
        env:
          PAT: ${{ secrets.PAT }}